CC = mingw32-g++.exe

Ejecutable:main.cpp Fecha.cpp SesionDClase.cpp
	mingw32-g++.exe -Wall -fexceptions -g -Iinclude -c main.cpp -o main.o
	mingw32-g++.exe -Wall -fexceptions -g -Iinclude -c Fecha.cpp -o Fecha.o
	mingw32-g++.exe -Wall -fexceptions -g -Iinclude -c SesionDClase.cpp -o SesionDClase.o
	mingw32-g++.exe  -o ProyectoPA_02.exe main.o Fecha.o SesionDClase.o

